name: "Terragrunt Destroy CI"

on:
  push:
    paths:
      - 'destroy-clusters/azure/**'
    branches:
      - main
  pull_request:
    types: [review_requested]
    paths:
      - 'destroy-clusters/azure/**'
    branches:
      - main

jobs:
  Terragrunt:
    name: "Terragrunt Destroy"
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      # Install the latest version of Terraform and Terragrunt CLI
      - name: Setup Terraform v1.4.0
        uses: hashicorp/setup-Terraform@v1
        with:
          terraform_version: 1.4.0
          terraform_wrapper: false
      - name: Setup Terraform version
        run: terraform --version
      - name: Setup Terraform wrapper path
        run: which terraform

      - name: Setup Terragrunt v0.44.5
        run: |
          sudo wget -q -O /bin/terragrunt "https://github.com/gruntwork-io/terragrunt/releases/download/v0.44.5/terragrunt_linux_amd64"
          sudo chmod +x /bin/terragrunt
          terragrunt -v

      - name: Get dependencies
        run: |
          git config --global url."https://${{ secrets.PAT}}@github.com/".insteadOf "ssh://git@github.com"
          git config --global http.sslVerify false

      # Setup AZURE credentials for the clusters
      - name: Az CLI login
        run: az login --service-principal -u 54ca77d8-81d5-4f61-94e0-77d00f5ea594 -p fBD8Q~csC09u.GzEfIr4caq1X6ccsRbGIVBZ2bSx --tenant d7d915d2-840b-42e3-b88c-a110aac3c1df

      # List of files that are added or modified in the commit
      - id: files
        uses: masesgroup/retrieve-changed-files@v2
      - run: |
          for added_modified_file in ${{ steps.files.outputs.all }}; do
            echo ${added_modified_file}
          done

      - id: sort
        run: |
          readarray -td $'\0' sorted < <(
                    for i in ${{ steps.files.outputs.all }};
                    do     printf '%s %s\0' "${#i}" "$i";
                    done |
                            sort -bz -k1,1nr -k2r|
                            cut -zd " " -f2-
                    )
          echo ${sorted[@]}
          echo "files=`echo ${sorted[@]}`" >> "$GITHUB_OUTPUT"

      # Initialize a new or existing Terragrunt working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terragrunt Init
        env:
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          cd 
          for added_modified_file in ${{ steps.sort.outputs.files  }}; do
            if [[ $(basename ${added_modified_file}) == 'terragrunt.hcl' ]]; then
            cd work/$REPO_NAME/$REPO_NAME
            pwd 
            file_name=$(dirname ${added_modified_file} | cut -d'/' -f3)
            echo ${added_modified_file}
            cd $(dirname ${added_modified_file})
            terragrunt init --terragrunt-non-interactive
            cd
            fi
          done 

      - name: Terragrunt Destroy
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          cd 
          for added_modified_file in ${{ steps.sort.outputs.files  }}; do
            if [[ $(basename ${added_modified_file}) == 'terragrunt.hcl' ]]; then
            cd work/$REPO_NAME/$REPO_NAME
            echo ${added_modified_file}
            file_name=$(dirname ${added_modified_file} | cut -d'/' -f3)
            echo ${added_modified_file}
            cd $(dirname ${added_modified_file})
            terragrunt destroy -auto-approve
            cd
            fi
          done

      - name: Clean up the Destroyed Cluster Folders
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          rm -rfv /home/runner/work/$REPO_NAME/$REPO_NAME/destroy-clusters/azure/*   

      - name: Auto Commit
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Remove destroyed clusters folders
